-- | The inference level (epsilon) operates in Diff: the category of
--   tensor spaces with smooth (differentiable) maps.
--
--   This is distinct from Tens at the domain level (gamma), which
--   allows all functions (including non-smooth ones like labelA).
--
--   The inference vocabulary symbols (softplus, crossEntropy, convex)
--   must be smooth because the chain rule propagates gradients through them:
--
--     theta --smooth---> h_theta(x) --smooth---> lossKnow([[phi]]_theta) -> R
--
--   Everything on the path from theta to the loss must be in Diff.
--   Data-providing functions (labels, encodings) live in Tens and
--   are treated as constants during differentiation.
module E_Inferential.A_Category.Diff () where
